<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => '主頁',
    'About' => '關於',
    'Contact' => '接觸',
    'Login' => '登錄',
    'English' => '英语',
    'Thai' => '泰国',
    'Chinese' => '中国人',
    'Japanese' => '日本人',
    'My Yii Application' => '我的 Yii 应用程序',

    'Admin System' => '管理系统',
    'Dashboard' => '仪表板',
    'People' => '人们',
    'Create' => '创建',
    'Status' => '状态',
];
